apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-spark-config"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
data:
{{ (.Files.Glob "config/*").AsConfig | indent 2 }}
  spark-defaults.conf: |
{{ include "spark-defaults-conf" . | indent 4 }}