# Default values for spark.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
global:
  image: minh5/kudu
  imageTag: latest
  pullPolicy: IfNotPresent
master:
  name: master
  replicas: 1
  component: "kudu-master"
  cpu: "100m"
  memory: "512Mi"
  servicePort: 7051
  containerPort: 7051
webUi:
  masterUi:
    name: master-ui
    servicePort: 8051
    containerPort: 8051
  workerUi:
    name: worker-ui
    servicePort: 8050
    containerPort: 8050
worker:
  name: worker
  replicas: 1
  component: "kudu-worker"
  cpu: "100m"
  memory: "512Mi"
  servicePort: 7050
  containerPort: 7050
  kuduMaster: kudu-master
persistence:
  enabled: true
  storageClass: generic
  accessMode: ReadWriteOnce
  size: 8Gi